### ISSUE TITLE
Adding more autoban URLs

### ISSUE THREAD

**Issue by Webx123** [GoelBiju/pinybot#58] opened 2016-12-31 06:28 UTC
the bot autobans when someone post a tinychat url how do i add more urls to that so it autobans more urls like that 
example what if i wanted the bot to ban all urls from a specific website.

**Comment by GoelBiju** [comment] 2016-12-31 17:51
@Webx123 , this could be a feature that could be added to the bot. It sounds like a great idea!

**Comment by Webx123** [comment] 2017-01-01 00:42
theres not a area of the code i can add to add it now?

**Comment by GoelBiju** [comment] 2017-01-01 23:21
Hi @Webx123 , sure there are plenty of ways (I think at least 😄 ) to add it to the code currently. @Autotonic mentioned this great website for testing out regex (http://www.regexr.com/). I did use it for the next version, but since the next version is currently broken, it may take some time for me to even figure out what the issue is.

This is the [line](https://github.com/GoelBiju/pinybot/blob/master/pinybot.py#L528) which checks if the Tinychat name is present in the message. You don't need regex, you could (I think):

```python
if '[your website name/url here]' in msg:
    self.send_ban_msg(user.nick, user.id)
```

Alternatively, maybe you could setup a list before the check, e.g. 

```python

auto_ban_url_list = ['awebsite.com', 'another-website.com']

for ban_website in auto_ban_url_list:
    if ban_website in msg:
        self.send_ban_msg(user.nick, user.id)
```

Give it a try yourself, I don't quite know how it will react or work, so it will worth finding out. Happy New Year as well! 🎆

**Comment by NawtJ0sh** [comment] 2017-01-02 13:12
Wonder if you can limit the lines the bot prints to the room for the urb, instead of banning the user, or it saying "This is a restricted term"

**Comment by NawtJ0sh** [comment] 2017-01-02 13:14
oh wait, this is talking about urls, nvm.

**Comment by GoelBiju** [comment] 2017-01-02 14:07
@NawtJ0sh  we have just done this by limiting amount of characters some functions return. Thanks for helping out!

**Comment by nortxort** [comment] 2017-01-08 21:38
Is there a reason why ban strings can't be used for this thing with URLs? I mean, since a URL is a string anyway and usually do not contain a space.

**Comment by Webx123** [comment] 2017-01-08 23:58
i tried setting it as a banend string and it still let them post it didnt work at all

**Comment by nortxort** [comment] 2017-01-10 22:56
@Webx123 try this. 

```python 

def check_msg_for_bad_string(self, msg, pm=False):
    """
    Checks the chat message for bad string.
    :param msg: str the chat message.
    :param pm: boolean true/false if the check is for a pm or not.
    """
    was_banned = False
    msg_words = msg.split(' ')
    bad_strings = pinylib.fh.file_reader(CONFIG['path'], CONFIG['badstrings'])
    for bad in bad_strings:
        if bad.startswith('*'):
            _ = bad.replace('*', '')
            if _ in msg:
                self.send_ban_msg(self.user_obj.nick, self.user_obj.id)
                was_banned = True
                if not pm:
                    self.send_bot_msg(special_unicode['toxic'] + ' *Auto-banned*: (*bad string in message)',
                                      self.is_client_mod)
        elif bad in msg_words:
            self.send_ban_msg(self.user_obj.nick, self.user_obj.id)
            was_banned = True
            if not pm:
                self.send_bot_msg(special_unicode['toxic'] + ' *Auto-banned*: (bad string in message)',
                                  self.is_client_mod)
    if was_banned and CONFIG['bsforgive']:
        self.send_forgive_msg(self.user_obj.id)

```

Usage `!bs *domain.com`  This will ban users sending messages containing domain.com
It is how i have done it in tinybot.

**Comment by GoelBiju** [comment] 2017-01-18 01:02
@nortxort , made a great point as this is probably the better way to handle it. I am closing this for now.

**Closed by GoelBiju** 2017-01-18 01:02 UTC
Labels: Beta
